#!/usr/bin/env bash
# mqvi — Full server one-command installer for Linux.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/akinalpfdn/Mqvi/main/deploy/install.sh | sudo bash
#
# What this does:
#   1. Creates /opt/mqvi and a dedicated 'mqvi' system user
#   2. Downloads the latest mqvi-server binary from GitHub releases
#   3. Downloads the LiveKit SFU binary
#   4. Generates .env with random JWT_SECRET and ENCRYPTION_KEY
#   5. Writes livekit.yaml with random API credentials
#   6. Installs systemd units for both services
#   7. Opens firewall ports (UFW / firewalld if present)
#   8. Starts both services
#
# Re-running is safe: existing .env and livekit.yaml are preserved.

set -euo pipefail

REPO="akinalpfdn/Mqvi"
INSTALL_DIR="/opt/mqvi"
DATA_DIR="${INSTALL_DIR}/data"
SERVICE_USER="mqvi"
LIVEKIT_VERSION="v1.9.12"
MQVI_PORT="9090"

log()  { printf '\033[1;34m[mqvi]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[mqvi]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[mqvi]\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "This script must be run as root. Try: sudo bash install.sh"

# ─── Detect architecture ─────────────────────────────────────────────────────
case "$(uname -m)" in
    x86_64|amd64)  ARCH="amd64" ;;
    aarch64|arm64) ARCH="arm64" ;;
    *) die "Unsupported architecture: $(uname -m). mqvi supports x86_64 and arm64." ;;
esac
log "Detected architecture: ${ARCH}"

# ─── Required tools ──────────────────────────────────────────────────────────
for tool in curl tar openssl systemctl; do
    command -v "$tool" >/dev/null 2>&1 || die "Missing required tool: $tool"
done

# ─── Create service user ─────────────────────────────────────────────────────
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
    log "Creating system user '${SERVICE_USER}'..."
    useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
fi

mkdir -p "$INSTALL_DIR" "$DATA_DIR/uploads"

# ─── Download mqvi-server binary ─────────────────────────────────────────────
MQVI_URL="https://github.com/${REPO}/releases/latest/download/mqvi-server-linux-${ARCH}"
log "Downloading mqvi-server (linux-${ARCH})..."
curl -fsSL --retry 3 -o "${INSTALL_DIR}/mqvi-server" "$MQVI_URL" \
    || die "Failed to download mqvi-server from ${MQVI_URL}"
chmod +x "${INSTALL_DIR}/mqvi-server"

# ─── Download LiveKit binary ─────────────────────────────────────────────────
if [ ! -x "${INSTALL_DIR}/livekit-server" ]; then
    LK_URL="https://github.com/livekit/livekit/releases/download/${LIVEKIT_VERSION}/livekit_${LIVEKIT_VERSION#v}_linux_${ARCH}.tar.gz"
    log "Downloading LiveKit ${LIVEKIT_VERSION}..."
    curl -fsSL --retry 3 "$LK_URL" | tar xz -C "$INSTALL_DIR" livekit-server \
        || die "Failed to download LiveKit from ${LK_URL}"
    chmod +x "${INSTALL_DIR}/livekit-server"
fi

# ─── Generate livekit.yaml (if absent) ───────────────────────────────────────
if [ ! -f "${INSTALL_DIR}/livekit.yaml" ]; then
    log "Generating livekit.yaml with random credentials..."
    LK_API_KEY="APIkey$(openssl rand -hex 6)"
    LK_API_SECRET="$(openssl rand -hex 32)"
    cat > "${INSTALL_DIR}/livekit.yaml" <<EOF
port: 7880

rtc:
  port_range_start: 50000
  port_range_end: 50200
  use_external_ip: true

keys:
  ${LK_API_KEY}: ${LK_API_SECRET}

logging:
  level: info

audio:
  active_level: 45
  min_percentile: 30
  update_interval: 200
  smooth_intervals: 2
EOF
else
    log "Existing livekit.yaml found — keeping it."
    LK_API_KEY=""
    LK_API_SECRET=""
fi

# ─── Generate .env (if absent) ───────────────────────────────────────────────
if [ ! -f "${INSTALL_DIR}/.env" ]; then
    log "Generating .env with random secrets..."
    JWT_SECRET="$(openssl rand -hex 32)"
    ENCRYPTION_KEY="$(openssl rand -hex 32)"
    cat > "${INSTALL_DIR}/.env" <<EOF
# mqvi Server Configuration — generated by install.sh

SERVER_HOST=0.0.0.0
SERVER_PORT=${MQVI_PORT}

DATABASE_PATH=${DATA_DIR}/mqvi.db

JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_EXPIRY_MINUTES=15
JWT_REFRESH_EXPIRY_DAYS=7

ENCRYPTION_KEY=${ENCRYPTION_KEY}

UPLOAD_DIR=${DATA_DIR}/uploads
UPLOAD_MAX_SIZE=26214400

# Auto-seed a LiveKit instance on first start so voice works out of the box.
# Remove these three lines if you want to manage LiveKit servers via the admin panel instead.
EOF
    if [ -n "$LK_API_KEY" ]; then
        cat >> "${INSTALL_DIR}/.env" <<EOF
LIVEKIT_URL=ws://127.0.0.1:7880
LIVEKIT_API_KEY=${LK_API_KEY}
LIVEKIT_API_SECRET=${LK_API_SECRET}
EOF
    fi
    chmod 600 "${INSTALL_DIR}/.env"
else
    log "Existing .env found — keeping it."
fi

chown -R "${SERVICE_USER}:${SERVICE_USER}" "$INSTALL_DIR"

# ─── systemd units ───────────────────────────────────────────────────────────
log "Installing systemd units..."
cat > /etc/systemd/system/mqvi-livekit.service <<EOF
[Unit]
Description=mqvi — LiveKit SFU
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/livekit-server --config ${INSTALL_DIR}/livekit.yaml
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=${INSTALL_DIR}

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/mqvi-server.service <<EOF
[Unit]
Description=mqvi — Application server
After=network-online.target mqvi-livekit.service
Wants=network-online.target
Requires=mqvi-livekit.service

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
EnvironmentFile=${INSTALL_DIR}/.env
ExecStart=${INSTALL_DIR}/mqvi-server
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=${DATA_DIR}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable mqvi-livekit.service mqvi-server.service >/dev/null

# ─── Firewall ────────────────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
    log "Opening UFW ports..."
    ufw allow "${MQVI_PORT}"/tcp   >/dev/null
    ufw allow 7880/tcp             >/dev/null
    ufw allow 7881/tcp             >/dev/null
    ufw allow 7882/udp             >/dev/null
    ufw allow 50000:50200/udp      >/dev/null
elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    log "Opening firewalld ports..."
    firewall-cmd --permanent --add-port="${MQVI_PORT}"/tcp >/dev/null
    firewall-cmd --permanent --add-port=7880/tcp           >/dev/null
    firewall-cmd --permanent --add-port=7881/tcp           >/dev/null
    firewall-cmd --permanent --add-port=7882/udp           >/dev/null
    firewall-cmd --permanent --add-port=50000-50200/udp    >/dev/null
    firewall-cmd --reload >/dev/null
else
    warn "No supported firewall detected. Manually open: ${MQVI_PORT}/tcp, 7880/tcp, 7881/tcp, 7882/udp, 50000-50200/udp"
fi

# ─── Start services ──────────────────────────────────────────────────────────
log "Starting services..."
systemctl restart mqvi-livekit.service
sleep 1
systemctl restart mqvi-server.service
sleep 2

if ! systemctl is-active --quiet mqvi-server.service; then
    warn "mqvi-server did not start. Check logs: journalctl -u mqvi-server -n 50"
    exit 1
fi

# ─── Done ────────────────────────────────────────────────────────────────────
PUBLIC_IP="$(curl -fsSL --max-time 3 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"

cat <<EOF

╔════════════════════════════════════════════════════════════╗
║  mqvi is installed and running.                            ║
╠════════════════════════════════════════════════════════════╣
║  Web UI:    http://${PUBLIC_IP}:${MQVI_PORT}
║  Install:   ${INSTALL_DIR}
║  Data:      ${DATA_DIR}
║
║  Logs:      journalctl -u mqvi-server -f
║  Restart:   systemctl restart mqvi-server
║  Stop:      systemctl stop mqvi-server mqvi-livekit
║
║  The first user to register becomes the server owner.
║  For HTTPS, put Caddy or nginx in front of port ${MQVI_PORT}.
╚════════════════════════════════════════════════════════════╝

EOF
